# Generated by Django 4.2.5 on 2023-10-01 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsdetails',
            name='end_datetime',
            field=models.TimeField(default=django.utils.timezone.now, help_text='End Time When doctor sits in the clinic'),
        ),
        migrations.AlterField(
            model_name='doctorsdetails',
            name='start_datetime',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Start Time When doctor sits in the clinic'),
        ),
    ]
