# Generated by Django 4.2.5 on 2023-10-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentApp', '0002_alter_doctorsdetails_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsdetails',
            name='available_slots',
            field=models.IntegerField(default=None, help_text='Number of Patients Doctor Check'),
        ),
    ]
