# Generated by Django 4.2.5 on 2023-10-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentApp', '0005_alter_doctorsdetails_available_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsdetails',
            name='available_slots',
        ),
    ]
