# Generated by Django 4.2.5 on 2023-10-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentApp', '0011_doctorsdetails_available_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsdetails',
            name='available_slots',
            field=models.IntegerField(default=0, help_text='Number of Patients Doctor Check'),
        ),
    ]
