# Generated by Django 4.2.5 on 2023-10-01 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentApp', '0012_alter_doctorsdetails_available_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbookings',
            name='doctor_appointed',
            field=models.ForeignKey(blank=True, help_text='Doctor Appointed', null=True, on_delete=django.db.models.deletion.CASCADE, to='AppointmentApp.doctorsdetails'),
        ),
    ]
